// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEhkNC-zNNV81xkp5rbP-2v7RQtrAxr-o',
    appId: '1:84573574582:web:95145b053f9c9b13dc1d17',
    messagingSenderId: '84573574582',
    projectId: 'book-selling-e3de4',
    authDomain: 'book-selling-e3de4.firebaseapp.com',
    storageBucket: 'book-selling-e3de4.firebasestorage.app',
    measurementId: 'G-R2YTD26TVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWTHSSv-QHwcmZ3l1dKHA7DUiCKVEqV-k',
    appId: '1:84573574582:android:c5ddaa8407dc6f61dc1d17',
    messagingSenderId: '84573574582',
    projectId: 'book-selling-e3de4',
    storageBucket: 'book-selling-e3de4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt2GpX_vzux65mL3f5pLS9GltIpSHVSys',
    appId: '1:84573574582:ios:a61ea7b3345379eedc1d17',
    messagingSenderId: '84573574582',
    projectId: 'book-selling-e3de4',
    storageBucket: 'book-selling-e3de4.firebasestorage.app',
    iosBundleId: 'com.example.bookApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt2GpX_vzux65mL3f5pLS9GltIpSHVSys',
    appId: '1:84573574582:ios:a61ea7b3345379eedc1d17',
    messagingSenderId: '84573574582',
    projectId: 'book-selling-e3de4',
    storageBucket: 'book-selling-e3de4.firebasestorage.app',
    iosBundleId: 'com.example.bookApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEhkNC-zNNV81xkp5rbP-2v7RQtrAxr-o',
    appId: '1:84573574582:web:dc3173f708607894dc1d17',
    messagingSenderId: '84573574582',
    projectId: 'book-selling-e3de4',
    authDomain: 'book-selling-e3de4.firebaseapp.com',
    storageBucket: 'book-selling-e3de4.firebasestorage.app',
    measurementId: 'G-54RYED1BXZ',
  );

}